---
title: "block_silhouette_perceptual_chunks"
author: "wmccarthy & jefan"
date: "5/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(broom)
library(tidyverse)
library(tidyboot)
library(knitr)
library(ggplot2)
library(ggthemes)
library(broom)
library(lme4)
library(lmerTest)
library(numform)
knitr::opts_chunk$set(echo = TRUE)
```

## Import data and apply preprocessing

```{r import}
df.proc.chunks = read.csv('../results/silhouette/csv/proc_chunk_use_separate_phases_2to6_perc_counts.csv') %>% 
  mutate(phase=factor(phase, levels=c('pre','post')))

# same data, grouped by 'gameID','phase','targetName','chunk_window' and summed
df.proc.chunks.sums = read.csv('../results/silhouette/csv/summed_proc_chunk_use_separate_phases_2to6.csv') %>% 
  mutate(phase=factor(phase, levels=c('pre','post')))
```

```{r}
df.proc.chunks <- df.proc.chunks %>% 
   mutate(perceptual_chunk=factor(df.proc.chunks$perceptual_count > 3))
```

```{r}
## fit model to data
m1 <- lmer(data = df.proc.chunks.sums, built_by_ppt ~ phase + (1 | gameID) + (1 + phase | targetName))
m2 <- lmer(data = df.proc.chunks.sums, built_by_ppt ~ chunk_window + (1 | gameID) + (1 + phase | targetName))
m3 <- lmer(data = df.proc.chunks.sums, built_by_ppt ~ phase + chunk_window + (1 | gameID) + (1 + phase | targetName))
m4 <- lmer(data = df.proc.chunks.sums, built_by_ppt ~ phase*chunk_window + (1 | gameID) + (1 + phase | targetName))
anova(m1,m2,m3,m4)
summary(m4)
```
```{r}
## Trying a logistic regression on whether or not chunk is built by remaining participant, rather than using the count (across all participants)
m1 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase + (1 | gameID) + (1 + phase | targetName))
m2 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ chunk_window + (1 | gameID) + (1 + phase | targetName))
m3 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase + chunk_window + (1 | gameID) + (1 + phase | targetName))
m4 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase*chunk_window + (1 | gameID) + (1 + phase | targetName))
anova(m1,m2,m3,m4)
summary(m4)
```

```{r}
## Trying a logistic regression on whether or not chunk is built by remaining participant, rather than using the count (across all participants)
m1 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase + (1 | gameID) + (1 + phase | targetName))
m2 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase + perceptual_chunk + (1 | gameID) + (1 + phase | targetName))
m3 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase*chunk_window + phase*perceptual_chunk + (1 | gameID) + (1 + phase | targetName))
anova(m1,m2,m3)
summary(m3)
```

```{r}
## Trying a logistic regression on whether or not chunk is built by remaining participant, rather than using the count (across all participants)
# m1 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase + (1 | gameID) + (1 + phase | targetName))
# m2 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ chunk_window + (1 | gameID) + (1 + phase | targetName))
# m3 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase + chunk_window + (1 | gameID) + (1 + phase | targetName))
m4 <- glmer(data = df.proc.chunks, family=binomial, built_by_ppt ~ phase*chunk_window + perceptual_count + (1 | gameID) + (1 + phase | targetName))
# anova(m1,m2,m3,m4)
summary(m4)
```


```{r import.perf}
df.proc.chunks.perf = read.csv('../results/silhouette/csv/proc_chunk_use_separate_phases_2to6_perfect_perc_counts.csv')

# same data, grouped by 'gameID','phase','targetName','chunk_window' and summed
df.proc.chunks.sums.perf = read.csv('../results/silhouette/csv/summed_proc_chunk_use_separate_phases_2to6_perfect.csv') %>% 
  mutate(phase=factor(phase, levels=c('pre','post')))
```

```{r}
## fit model to data
m1 <- lmer(data = df.proc.chunks.sums.perf, built_by_ppt ~ phase + (1 | gameID) + (1 + phase | targetName))
m2 <- lmer(data = df.proc.chunks.sums.perf, built_by_ppt ~ chunk_window + (1 | gameID) + (1 + phase | targetName))
m3 <- lmer(data = df.proc.chunks.sums.perf, built_by_ppt ~ phase + chunk_window + (1 | gameID) + (1 + phase | targetName))
m4 <- lmer(data = df.proc.chunks.sums.perf, built_by_ppt ~ phase*chunk_window + (1 | gameID) + (1 + phase | targetName))
anova(m1,m2,m3,m4)
summary(m4)
```

```{r}
## Trying a logistic regression on whether or not chunk is built by remaining participant, rather than using the count (across all participants)
m1 <- glmer(data = df.proc.chunks.perf, family=binomial, built_by_ppt ~ phase + (1 | gameID) + (1 + phase | targetName))
m2 <- glmer(data = df.proc.chunks.perf, family=binomial, built_by_ppt ~ chunk_window + (1 | gameID) + (1 + phase | targetName))
m3 <- glmer(data = df.proc.chunks.perf, family=binomial, built_by_ppt ~ phase + chunk_window + (1 | gameID) + (1 + phase | targetName))
m4 <- glmer(data = df.proc.chunks.perf, family=binomial, built_by_ppt ~ phase*chunk_window + (1 | gameID) + (1 + phase | targetName))
anova(m1,m2,m3,m4)
summary(m4)
```

```{r}

```
