---
title: "block_silhouette_cogsci2020"
author: "wmccarthy & jefan"
date: "1/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(broom)
library(tidyverse)
library(knitr)
library(ggplot2)
library(broom)
library(lme4)
library(lmerTest)
knitr::opts_chunk$set(echo = TRUE)
```

## Import data and apply preprocessing

```{r import}
df.full = read.csv('../results/csv/block_silhouette_Exp2Pilot3.csv')
bis.full = read.csv('../results/csv/block_silhouette_bis_Exp2Pilot3.csv')


d <- df.full %>% 
  select(rawF1DiscreteScore,phase,condition,trialNum,targetName,gameID, repetition,blockFell,buildTime) %>% 
  rename('accuracy'='rawF1DiscreteScore') %>%
  mutate(phase=relevel(phase, ref='pre')) %>% 
  mutate(blockFell = as.logical(blockFell)) %>%
  filter(phase %in% c('pre','post'))

b <- bis.full %>%
  filter(phase %in% c('pre','post'))

b
```

## Inspect data frame
```{r}
b %>% group_by(phase) %>% tally()
``` 


## Modeling effect of phase x condition on accuracy (F1 score)

Linear mixed effects models predicting rawF1DiscreteScore
```{r lmers}
m1 <- lmer(data = d, accuracy ~ phase + (1 | gameID) + (1 | targetName))
m2 <- lmer(data = d, accuracy ~ condition + (1 | gameID) + (1 | targetName))
m3 <- lmer(data = d, accuracy ~ phase + condition + (1 | gameID) + (1 | targetName))
m4 <- lmer(data = d, accuracy ~ phase * condition + (1 | gameID) + (1 | targetName))
anova(m1,m2,m3,m4)
summary(m4)
```

## Modeling effect of phase x condition on build time 
```{r}
lmm <- lmer(data = d, buildTime ~ phase*condition  + (1 | gameID) + (1 | targetName))
summary(lmm)
```

## Model effect of phase * condition on BIS
```{r}
m4 <- lmer(data = b, bis ~ phase*condition + (1 | targetName))
summary(m4)
```

## Visualize accuracy timecourse
```{r}

```

